# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Mobile Photography by Ziad Rahman Bhuiyan"
subtitle: "See the world through my eyes!"
author:  "Ziad Rahman Bhuiyan"
header:
 title: "Mobile Photography"
 subtitle: "by Ziad Rahman Bhuiyan"
footer:
 name: "Hey there, I am Ziad Rahman Bhuiyan "
 bio: "WRITER || ESSAYIST || BLOGGER || SOCIAL WORKER || RESEARCHER || SPORTSMAN || PROGRAMMER || OLYMPIADIAN || PHOTOGRAPHER || ARTIST || CALLIGRAPHER || TRAVELLER"
social_urls:
  facebook: "https://www.facebook.com/profile.php?id=61557838765203&mibextid=ZbWKwL"
  twitter: "https://twitter.com/Ziad_Bhuiyan"
  #instagram: "https://www.instagram.com/devesh.sangwan/"
  linkedin: "https://www.linkedin.com/in/ziad-rahman-bhuiyan/"
  github: "https://ziad786.github.io/"


theme: jekyll-theme-slate
